### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by SergeGardien** [dleshem/freemazon#1]
I've tried to execute the JS with Node.js (both under Eclipse and via OSX Terminal) but I got the error:
`SyntaxError: Unexpected token import`

@dleshem , do you have the same issue?

**Comment by dleshem** [comment]
```import``` is ES6 syntax that's not supported natively by node. You can use a transpiler like https://babeljs.io/ to convert the code to ES5.

Since this code is educational in nature, I have no intention to make it ES5 compliant.

**Comment by SergeGardien** [comment]
Yes, I was already trying to use Babel (I've read a few posts around the web) but it seems I cannot make it work.
I'll try to figure it out.

Tx for the reply
